// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYXFoJxuCVJn3_hKZDlT4mHKoIbtv78mM',
    appId: '1:235931425275:web:85af10883405439cfa135e',
    messagingSenderId: '235931425275',
    projectId: 'smart-press-674b2',
    authDomain: 'smart-press-674b2.firebaseapp.com',
    storageBucket: 'smart-press-674b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiGbNVZF1Hv4ISMQ3mI7YAlTLZAcZ7Wx8',
    appId: '1:235931425275:android:74d1d3d254a1d310fa135e',
    messagingSenderId: '235931425275',
    projectId: 'smart-press-674b2',
    storageBucket: 'smart-press-674b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFcOkauDPMqv4mDtQ3s3j4Isdb1p6bXs',
    appId: '1:235931425275:ios:090206f1990e121ffa135e',
    messagingSenderId: '235931425275',
    projectId: 'smart-press-674b2',
    storageBucket: 'smart-press-674b2.firebasestorage.app',
    iosBundleId: 'com.example.smartPress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFcOkauDPMqv4mDtQ3s3j4Isdb1p6bXs',
    appId: '1:235931425275:ios:090206f1990e121ffa135e',
    messagingSenderId: '235931425275',
    projectId: 'smart-press-674b2',
    storageBucket: 'smart-press-674b2.firebasestorage.app',
    iosBundleId: 'com.example.smartPress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYXFoJxuCVJn3_hKZDlT4mHKoIbtv78mM',
    appId: '1:235931425275:web:0fef83952dad4177fa135e',
    messagingSenderId: '235931425275',
    projectId: 'smart-press-674b2',
    authDomain: 'smart-press-674b2.firebaseapp.com',
    storageBucket: 'smart-press-674b2.firebasestorage.app',
  );
}
